name: Build representations with MITI tools

on:
  pull_request:
    paths:
      - 'yaml/**'

jobs:
  tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install git+https://github.com/miti-consortium/mititools.git
          mititools generate --source-dir yaml/
          git add cv/ flatfields/ frictionless/ example_fd_package/
          git commit -m "Automated representation builds"
          git push ${{ github.event.pull_request.head.repo.full_name }} ${{ github.head_ref }}
